name: cell_culture_app
description: Cell culture template app
publish_to: "none"

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  excel: ^4.0.6
  path_provider: ^2.1.5

flutter:
  uses-material-design: true